#!/bin/bash

set -e
[[ $DEBUG ]] && set -x

source ansible/hacking/env-setup

HERE="$(
  python -c \
    "import os.path;print os.path.dirname(os.path.abspath('$0'))"
)"

TEST_PORT=$(echo ${RANDOM}${RANDOM} | cut -b1-4)
export TORY_SERVER=http://localhost:$TEST_PORT/ansible/hosts

$HERE/bin/json-server -p $TEST_PORT -d $PWD/.fake-tory >> server.log 2>&1 &
JSPID=$!
sleep ${JSON_SERVER_STARTUP_SLEEP:-1}

trap "kill -9 $JSPID" EXIT INT TERM


./ansible/hacking/test-module \
    -m ./tory_add_host \
    -a 'hostname=foo.example.com ip=10.10.1.1'

./ansible/hacking/test-module \
    -m ./tory_remove_host \
    -a 'hostname=foo.example.com'
